numerique-gouv/proconnect-landing-page

- README.md
- package-lock.json
- package.json
- vite.config.ts
<p align="center">
</p>
<p align="center">
@BenoitSerrano 
</p>
> Add config scalingo

- README.md
- package.json
- vite.config.ts
> Construire la landing ProCo de A à Z

- src/Datas.tsx
- src/components/Header/Header.tsx
- src/components/PrivateOrPublic/PrivateOrPublic.tsx
> Change link GitHub and add links to partners & annuaire

- package-lock.json
- package.json
DSFR package update from version 1.9.11 to 1.9.27.
> update @codegouvfr/react-dsfr package version 1.9.27

- .github/workflows/ci.yaml
- package.json
> chore: remove eslint

- package.json
> deploy: use npx serve

- package.json
Reverts numerique-gouv/proconnect-landing-page#16
> Revert "deploy: use npx serve"

- src/Datas.tsx
- src/Pages/HomeLayout.tsx
- src/Pages/Stats.tsx
- src/components/Buttons/ButtonRadius.tsx
- src/components/Card/Card.tsx
<p align="center"><img src="https://media.giphy.com/media/mEUX221NDJjvxeGMiL/giphy.gif?cid=790b7611fzxxcjk5hedmqnoytiw4sq403exfe4edsyq2rit9&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
> chore: remove unnecessary comments from the codebase

- src/Pages/Services/constants.ts
Rename descriptions for greater consistency (thx @BenoitSerrano) and add descriptions when there was none
> refactor: rename descriptions for services

- src/Pages/HomeLayout.tsx
<p align="center">Petite tension entre bouton et AgentConnect oups</p>
<p align="center"><img src="https://media.giphy.com/media/OhlQ6fgmMzp1gnjeFh/giphy.gif?cid=790b7611vraz0kve8zjg8gozya2t35u1u4vx2qo4xjn76egb&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
> fix(wording): add space between two words

- src/client/src/Pages/Services/Services.tsx
- src/client/src/Pages/Services/constants.ts
Hello !
Suite à une demande de Thibaud Chambert-Loir :
Merci !
> Ajout d'une catégorie "Suite territoriale"

- src/client/index.html
- src/client/src/Pages/Cgu.tsx
- src/client/src/Pages/LegalNotices.tsx
- src/client/src/Pages/WrapperLayout.tsx
- src/client/src/components/Footer/Footer.tsx
- src/client/src/components/Tiles/Tile.tsx
Update some code html and text (spelling shell), add attribute for pictures.
> Accessibility

- src/client/src/Pages/Accessibility.tsx
- src/client/src/Pages/AuthenticationError.tsx
- src/client/src/Pages/Cgu.tsx
- src/client/src/Pages/Eligibility/EligibilityTest.tsx
- src/client/src/Pages/HomeLayout.tsx
- src/client/src/Pages/LegalNotices.tsx
- src/client/src/Pages/MonCompte.tsx
- src/client/src/Pages/NotFound.tsx
- src/client/src/Pages/Roadmap.tsx
- src/client/src/Pages/Services/Services.tsx
- src/client/src/Pages/SiteMap.tsx
- src/client/src/Pages/Stats.tsx
- src/client/src/lib/useTitle.ts
https://trello.com/c/I3fQ74dj/2-titre-des-pages
> accessibility(title): add title for easy navigation

- src/app/app.ts
- src/client/src/Pages/Accessibility.tsx
- src/client/src/Pages/Cgu.tsx
- src/client/src/Pages/Eligibility/Result.tsx
- src/client/src/Pages/Eligibility/WhoIsYourBoss.tsx
- src/client/src/Pages/HomeLayout.tsx
- src/client/src/Pages/LegalNotices.tsx
- src/client/src/Pages/MonCompte.tsx
- src/client/src/Pages/Stats.tsx
- src/client/src/components/Header/NameChangeNotice.tsx
- src/client/src/components/HowDoesItWork/HowDoesItWork.tsx
- src/client/src/components/WantToIntegrateProConnect/WantToIntegrateProConnect.tsx
<p align="center"><img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDZpa2l6NWJibmlrbTliaXA1cXVrb2VzcGd2cjVkMXJmNmV0c2NkaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/B64XJ9RxJ6fSN94Neh/giphy.gif"></p>
> refactor: replace old mailto & links + clean &nbsp; 

- src/client/src/Pages/WrapperLayout.tsx
- src/client/src/components/Footer/Footer.tsx
- src/client/src/components/Header/Header.tsx
- src/client/src/components/SkipLinks/SkipLinks.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTV2emQ2NTZmZ2hzbGQ1OXR1czdwN3ZycWxtbmFnMjd1ejBqbm8ydCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/aYzxVt2lMrZXW/giphy.gif"></p>
> fix(a11y): add "formulaire de connexion" to skiplinks & create dedicated component 

- src/client/src/Pages/MonCompte.tsx
- src/client/src/components/WantToIntegrateProConnect/WantToIntegrateProConnect.tsx
<p align="center"><img src="https://media.giphy.com/media/Wowj1abwRkpSo/giphy.gif?cid=82a1493b1tzscw0e2c6a3o3fd939oxeoc6vwcu9wbk679wt6&ep=v1_gifs_trending&rid=giphy.gif&ct=g"></p>
> refactor(a11y): delete bad nesting of buttons and links

- src/client/src/Pages/Accessibility.tsx
- src/client/src/components/Footer/Footer.tsx
- src/client/src/components/WantToIntegrateProConnect/WantToIntegrateProConnect.tsx
<p align="center"><img src="https://media.giphy.com/media/tyxovVLbfZdok/giphy.gif?cid=82a1493btkohr77bh0vnmgk1flbx2b7tbzg7rrq0z2l73wn8&ep=v1_gifs_trending&rid=giphy.gif&ct=g"></p>
> a11y(links): Add target="_blank", title, rel="noreferrer noopener", keys on links

- src/client/src/Pages/Cgu.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYm1vdDQ2eDFoYjc2emlyMWhlbWc1dTM2cG43em1nZWxtZXRmbXloMSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/h7A9YxNGPCr3fjouNb/giphy.gif"></p>
> a11y(blockquote): Add <blockquote> element on cgu's quotes

- src/client/src/Pages/Cgu.tsx
<p align="center"><img src="https://media.giphy.com/media/nxixvW5krNTKLVOKDp/giphy.gif?cid=82a1493biecaeryr6wqzl3yhb25n9cedpyzmv9w5rwst2i22&ep=v1_gifs_trending&rid=giphy.gif&ct=g"></p>
> a11y(links): Add space around links, rel noreferrer & title in cgu

- src/client/src/Pages/MonCompte.tsx
- src/client/src/Pages/SiteMap.tsx
- src/client/src/Pages/SiteRecommandation/Result.tsx
- src/client/src/Pages/SiteRecommandation/SiteRecommandation.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjRuMzdpNnRkb3NrazUyazRweG1iMGppNmMzNHZ0cGgxcDBiZTdyMSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3ohze3kG5qO9DcTUbe/giphy.gif"></p>
> a11y(links): Delete class that deletes links style
